### ISSUE TITLE
Browser tests break when upgrading from 2.3.9 to 2.3.10

### ISSUE THREAD

**Issue by lsg-richard** [danielspaniel/ember-data-factory-guy#323]
Hi,

When using `ember-data-factory-guy` 2.3.9 all my tests pass when run with `yarn run ember test` and also when navigating to `localhost:4200/tests`. But when I upgrade to 2.3.10 the tests on `localhost:4200/tests` start failing but `yarn run ember test` still works fine.

I'm using headless Chrome not PhantomJS, and also using Chrome for the in-browser tests.

The errors I see are:

```
TypeError: setupContainer is not a function
    at exports.default (assets/test-support.js:36956:7)
    at _class._setupContainer (assets/test-support.js:38324:48)
    at _class._setupIsolatedContainer (assets/test-support.js:38344:14)
    at _class.setupContainer (assets/test-support.js:38183:16)
    at assets/test-support.js:36744:28
    at initializePromise (assets/vendor.js:67421:7)
    at new Promise (assets/vendor.js:67900:35)
    at nextStep (assets/test-support.js:36743:20)
    at _class.invokeSteps (assets/test-support.js:36750:16)
    at _class.setup (assets/test-support.js:36697:21)

TypeError: Cannot read property 'subject' of undefined
    at _class.teardownSubject (test-module.js:242)
    at abstract-test-module.js:101
    at initializePromise (rsvp.js:418)
    at new Promise (rsvp.js:897)
    at nextStep (abstract-test-module.js:100)
    at _class.invokeSteps (abstract-test-module.js:107)
    at abstract-test-module.js:65
    at tryCatcher (rsvp.js:215)
    at invokeCallback (rsvp.js:393)
    at rsvp.js:457

Uncaught TypeError: Cannot read property 'currentRetry' of undefined
    at mocha.js:5043
    at Runner.runTest (mocha.js:4936)
    at mocha.js:5040
    at next (mocha.js:4854)
    at mocha.js:4864
    at next (mocha.js:4796)
    at mocha.js:4832
    at timeslice (mocha.js:75)
```

Given that there was only one commit made between 2.3.9 and 2.3.10, https://github.com/danielspaniel/ember-data-factory-guy/commit/53b13675c5bff0870416c05dbebdf6ebfb143aef, and the only consequential change in that commit is the package switch from `ember-cli-pretender` to `pretender` and `resolve`, that seems like the probable culprit.

Any suggestions on a fix or workaround? For now I'm just staying on 2.3.9.

The rest of the application is on Ember 2.18, and Ember Data 2.18. I also tried Ember and Ember Data 2.16.3 and saw the same issue.

Thanks.

**Comment by lsg-richard** [comment]
Should also add that the issue persists in the latest version 2.13.22. First appeared in 2.3.10 though.

**Comment by danielspaniel** [comment]
This is interesting issue. In order to fix it I need some way to reproduce it. So, I wonder if you could show me a test that fails. Your using mocha it looks like?  This should not be issue since I use ember-mocha in some projects as well. 
 I think you should be able to make a an ember twiddle  ( you can add addons now ) and hopefully reproduce that test in there?

**Comment by lsg-richard** [comment]
Ok I'll try to put together a simple app that demonstrates the issue.

If it's relevant the `ember-cli-mocha` version was 0.14.4.

Thanks.

**Comment by danielspaniel** [comment]
I am using that same version of mocha with latest factory guy and it works fine. So my guess is you are doing something that is different ( duh ) .. just a matter of finding out what that is.   If you don't mind me poking around your repo, I could do that, or if you make a sample repo that shows issue, that would do it too.

**Comment by danielspaniel** [comment]
Any more ideas @lsg-richard ?  Did you find solution?  Need more help? I am going to close this, but feel free to reopen if it is still a problem.

**Comment by lsg-richard** [comment]
Am still seeing this after upgrading to Ember / Ember Data 3 and the latest version of other packages. Will reopen once I have isolated a repro case. Thanks.

**Comment by danielspaniel** [comment]
Ok, great Richard, I would love to see a repo with this case reproduced. It is very curious, because I am on Ember 3 / Ed 3 and the latest everything and I have been upgrading steadily since forever and have never seen this issue.
